language: python
python:
  - "3.5"
#command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
- psql -c 'CREATE DATABASE stackoverflow;' -U postgres


#command to run tests
script:
  - nosetests --with-coverage

after_success:
  - coveralls

